### PR TITLE
Add initial image support 

### LINKED ISSUE #12: Add support for initial image
Support an initial image attribute which displays the image at the specified index initially when the gallery component is mounted.

Below example, loads the 3rd image initially
``` jsx
<ImageGallery items={images}
                        initialImage={2}/>
```

### PR DESCRIPTION
**Pull request by codematix**
Fixes #12 to add support for specifying an initial image when gallery component is mounted

### CODE REVIEW

**Comment by linxtion** [comment]
@codematix I'm curious why this is needed? You can just change the initial image by reordering the `items` prop.

**Comment by codematix** [comment]
@linxtion I had a use case for image gallery where a page was showing thumbnail images of products. The use case required that when the user clicks on any of the thumbnails on the page, a modal is displayed with a gallery which displays a zoomed-in version of the product image and also provide arrows to scroll. 

Now a product could have more than one image. Therefore, if the user clicks on the 3rd thumbnail on the page, I open the modal with the image gallery with the full version of the 3rd image and then allow scrolling to the remaining image.

If I re-order my `items` prop array, I will have to deal with affecting the model object shared by both the parent page and the image gallery component. Hence I felt it would be simpler to modify the image gallery component to give it an `initialImage` prop.

**Comment by linxtion** [comment]
@codematix fair enough, I left some comments in the code if you don't mind adjusting I can merge. Thanks.

**Comment by codematix** [comment]
@linxtion the review comments are implemented. Please consider merging. Thanks!

**Pull request merged**
