### PR TITLE
Added ability to show index

### PR DESCRIPTION
**Pull request by ryanmargheriti**
I added the ability for the user to show the index. This was useful for me , it may not be useful to anybody else, so feel free to reject it if you dont want it in the codebase. I also made the separator configurable.

### CODE REVIEW

**Comment by linxtion** [comment]
Looks useful, ill take a look sometime this weekend. Thanks!

**Comment by linxtion** [comment]
@ryanmargheriti Hey Ryan, looks really good, can you update, and rebase on master, then I can merge. Thanks.

**Comment by ryanmargheriti** [comment]
Should be good to go @linxtion

**Comment by linxtion** [comment]
Can you squash this into one commit? :+1:

**Comment by ryanmargheriti** [comment]
Done and done

**Comment by linxtion** [comment]
Thanks!

**Pull request merged**
