### PR TITLE
Add IE8 opacity styles and alternative for transform

### PR DESCRIPTION
**Pull request by heldinz**
Fixes bug where 'center' image was obscured by 'left'

### CODE REVIEW

**Comment by heldinz** [comment]
I've found a similar issue with thumbnails not scrolling: I'll fix that and then update the PR.

**Comment by linxtion** [comment]
cool, thanks for fixing the IE8 stuff!

**Comment by heldinz** [comment]
Ok, the only way I could get IE8 to scroll the thumbnail container properly was to set the `left` property where the other browsers use `transform: translate3d`. Unfortunately, the modern browsers of course apply both `left` and `translate3d`, leading to an incorrect result, so I ended up removing the transforms from the inline style completely and only using `left`. I'll happily change that if you have a suggestion!

**Comment by linxtion** [comment]
Sorry for getting back to you so late, been rather busy. I left some comments on the PR. Thanks!

**Comment by heldinz** [comment]
Sorry for being out of contact too! (Changed jobs, which also reduced the urgency of this issue for me.)

Anyway, I think a mustard cut test like the one you propose is a good idea. I'll try to update the PR next week.

**Comment by linxtion** [comment]
We no longer need to support IE8 Phewwwwwwwwwwww.

**Pull request closed without merging**
