### PR TITLE
Fixing width initialisation for the case that the image-gallery compo…

### PR DESCRIPTION
**Pull request by itayma**
…nent is loaded in a secondary tab + image sizes is reduced in the .css

### CODE REVIEW

**Comment by itayma** [comment]
The scenario is using the react-image-gallery in a tab which is not the active tab on page load.
The component is loaded but the containerWidth was not initialised yet.
In addition I reduced the css file to reduce the size of the actual pictures not to be 100%.
The result of the above combination caused the thumbnails container location to be set outside of the screen when it is calculated, and that's why I added the extra validation there.

**Comment by linxtion** [comment]
Can you attach a screenshot of what you mean? I'm confused, if the `containerWidth` is not yet initialized, then `thumbNode.scrollWidth <= this.state.containerWidth` should compute to `true` `0 <= 0`. If there is no containerWidth, there there is no thumbnails.

**Comment by itayma** [comment]
I will try to explain better my code and the reason for the confusion.
You are correct that 0 <= 0 will compute to true, but I have a value in thumbNode.scrollWidth bigger then 0

* I am loading a page with 3 Tabs. loading all the components of the 3 tabs on page load
* On load, the active tab is not the image gallery tab
 * The _handleResize is called setting the containerWidth to 0 (from componentDidMount)
* The user is choosing to view the tab with the image gallery
 * The _handleResize is not called again
* The user is swiping to the next image
 * _getScrollX is called
 * thumbNode.scrollWidth is calculated inside the _getScrollX method and is bigger then 0 
 * but containerWidth is still 0 -> Here is the problem

And that is why I added an extra validation there.

Hope this is a bit clearer and thanks again for the library of course.

**Comment by linxtion** [comment]
`_handleResize` is called when the component mounts. Is there a reason you load all the components of the 3 tabs, instead of loading them each as needed? For example if you have a tab view you could use the snippet below (untested).

```
var ImageGallery = require('react-image-gallery');
var ViewOne = require('./ViewOne.react.jsx');
var ViewTwo = require('./ViewTwo.react.jsx');

var TabView = React.createClass({

  getInitialState: function() {
    return {
      tab: 1
    };
  },

  _handleTabClick: function(idx) {
    if (this.state.tab !== idx) {
      this.setState({tab: idx});
    }
  },

  render: function() {

    var content;
    switch (this.state.tab) {
      case '1':
        content = (
          <ViewOne/>
        );
        break;
      case '2':
        content = (
          <ViewTwo/>
        );
        break;
      case '3':
        content = (
          <ImageGallery/>
        );
        break;
    }
    return (
      <div className='TabView'>
        <ul>
          <li>
            <a onClick={this._handleTabClick.bind(this, 1)}>
              Tab #1
            </a>
          </li>

          <li>
            <a onClick={this._handleTabClick.bind(this, 2)}>
              Tab #2
            </a>
          </li>

          <li>
            <a onClick={this._handleTabClick.bind(this, 3)}>
              Image Gallery
            </a>
          </li>
        </ul>

        <div className='TabViewContent'>
          {content}
        </div>
      </div>
    );
  }

});
```

**Comment by itayma** [comment]
I agree and changed my code to mount the image gallery component only when the relevant tab is clicked and it all works well. Thanks!

**Pull request closed without merging**
